version: "3.9"

services:
  object-detection:
    image: object-detection:latest
    build: .
    container_name: object-detection
    command: python -u object-face-detection.py

    env_file:
      - /opt/config/object-detection/.env

    volumes:
      - /opt/config/object-detection/image_detection:/app/image_detection

    network_mode: host
    restart: unless-stopped